import os
import sys
import subprocess
import glob
from os import path


## The function "readMap" reads in the map that    ##
## converts 1943 dim vector to 48 dimensions.      ##
## This function returns a 1943 dim vector, having ##
## integer content ranging from 0 to 47.           ##
def readMap(filename):
    f =  open(filename, 'r')
    index = []
    for i in f:
        part = i.split(',')
        index.append(int(part[1]))
    f.close()
    return index

## The function "mapping" reads in the vector  ##
## returned by function "readMap" as its input ##
## inputMap. The input inputVector has a dim   ##
## of 1943. The input outputDim is simply a    ##
## dummy variable, put integer "48" to it.     ##

def mapping(inputMap, inputVector, outputDim)
    if len(inputMap) == len(inputVector):
        output = []
        # Initialization of the output vector
        for i  in xrange(len(outputDim)):
            output.append(int(0))

        for i in xrange(len(inputVector))
            output[int(inputMap[i])] += inputVector[i]
        return output
        
    else:
        print: 'The input map/vector dimensions dont match...'
        return 0
    
## The function "mapping_one_dim" reads in an input    ##
## vector of arbitrary length, and a map "inputMap"    ##
## generated by the "readMap" function above. Elements ##
## of the input vector should range from 0 to 1942.    ##
## Elements of the output vector will range from 0 to  ##
## 47                                                  ##

def mapping_one_dim(inputMap, inputVector)
    output = []
    for i in xrange(len(inputVector)):
        output.append(inputMap(inputVector[i]))
    return output
